### PR TITLE
Clean up garden.py  

### PR DESCRIPTION
**Pull request by azbshiri**
Hey, I just became very interested in the language and I did some clean up to graden.py.

* Use strip() to remove quotes
* Remove all pesky PEP8

### CODE REVIEW

**Comment by justjoeyuk** [comment]
Thanks, was waiting for someone to teach me the ways! ;)

**Comment by azbshiri** [comment]
yeah, there is conflict because I've cloned the repository before your changes.

**Comment by azbshiri** [comment]
so I just pull the changes again and make a new branch then I send a pull request :+1:

**Comment by azbshiri** [comment]
you could just close this pull request.

**Comment by justjoeyuk** [comment]
@jesserayadkins

**Pull request closed without merging**
